import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
const url=process.env.INTRO_URL||'http://127.0.0.1:5188/sgs-it/';
const browser=process.env.BROWSER_HEADLESS==='1'?await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE,args:['--enable-unsafe-swiftshader']}):await chromium.connectOverCDP(process.env.BROWSER_CDP_URL||'http://127.0.0.1:9223');
const context=await browser.newContext({viewport:{width:1440,height:900},reducedMotion:'no-preference'});
const page=await context.newPage(),errors:string[]=[],checks:string[]=[];
page.on('pageerror',e=>errors.push(e.message));
await context.addInitScript(()=>{sessionStorage.setItem('sgs-intro','1');localStorage.setItem('sgs-cookies','essential-only');});
await mkdir('docs/research/intro',{recursive:true});
try{
 const html=await(await context.request.get(url)).text();
 for(const property of ['og:title','og:type','og:url','og:description','og:site_name','og:locale','og:image','og:image:secure_url','og:image:type','og:image:width','og:image:height','og:image:alt'])assert.match(html,new RegExp('property="'+property+'"'));
 assert.match(html,/name="twitter:card" content="summary_large_image"/);assert.match(html,/rel="canonical" href="https:\/\/sgsit.ru\/"/);
 const schema=JSON.parse(html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)![1]);assert.equal(schema['@graph'].length,3);assert.ok(schema['@graph'].some((x:any)=>x.legalName==='ООО «ВоркСинк Системс»'));checks.push('OG, Twitter, canonical and factual JSON-LD present in raw HTML');
 for(const asset of ['icon.svg','favicon.ico','favicon-32.png','apple-touch-icon.png','icon-192.png','icon-512.png','og/parkops-business-v1.jpg','robots.txt','sitemap.xml'])assert.equal((await context.request.get(new URL(asset,url).href)).status(),200,asset);checks.push('Share image, favicons, PWA icons, robots and sitemap served');
 page.setDefaultTimeout(20000);await page.goto(url);await page.bringToFront();const c=await context.newCDPSession(page);await c.send('Emulation.setFocusEmulationEnabled',{enabled:true});
 const intro=page.locator('.intro-sequence');await intro.waitFor();await page.waitForFunction(()=>document.querySelector('.terminal-welcome')?.textContent==='>welcome to new SAAS project ParkOps');await page.getByRole('button',{name:'Приостановить вступление',exact:true}).click();
 assert.match(await intro.innerText(),/>hello, Neo!/);assert.match(await intro.innerText(),/>welcome to new SAAS project ParkOps/);assert.equal(await intro.getAttribute('data-phase'),'0');await page.screenshot({animations:'disabled',path:'docs/research/intro/01-contact.png'});checks.push('Greeting remains readable; prior session flag does not suppress intro');
 for(const [width,height] of [[320,568],[390,844]]){await page.setViewportSize({width,height});assert.ok(await intro.evaluate(e=>e.scrollWidth<=e.clientWidth&&e.scrollHeight<=e.clientHeight+1),'Animated intro fits '+width);}
 await page.screenshot({animations:'disabled',path:'docs/research/intro/01-contact-mobile.png'});await page.setViewportSize({width:1440,height:900});
 const frozen=await intro.getAttribute('data-time');await page.waitForTimeout(1100);assert.equal(await intro.getAttribute('data-time'),frozen);checks.push('Pause stops story clock');
 await page.getByRole('button',{name:'Продолжить вступление',exact:true}).click();await page.getByText('parkops = clarity.connect(modules)',{exact:true}).waitFor();await page.getByRole('button',{name:'Приостановить вступление',exact:true}).click();assert.equal(await intro.getAttribute('data-phase'),'1');assert.match(await intro.innerText(),/parkops = clarity.connect\(modules\)/);await page.screenshot({animations:'disabled',path:'docs/research/intro/02-code.png'});
 await page.getByRole('button',{name:'Продолжить вступление',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.intro-sequence')?.getAttribute('data-phase')==='2');await page.waitForTimeout(1200);await page.getByRole('button',{name:'Приостановить вступление',exact:true}).click();assert.equal(await intro.getAttribute('data-phase'),'2');assert.equal(await intro.locator('.intro-module').count(),4);await page.screenshot({animations:'disabled',path:'docs/research/intro/03-8bit.png'});
 await page.getByRole('button',{name:'Продолжить вступление',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.intro-sequence')?.getAttribute('data-phase')==='3');await page.waitForTimeout(1200);await page.getByRole('button',{name:'Приостановить вступление',exact:true}).click();assert.equal(await intro.getAttribute('data-phase'),'3');assert.equal(await intro.locator('.intro-blue-core').evaluate(e=>getComputedStyle(e).opacity),'1');await page.screenshot({animations:'disabled',path:'docs/research/intro/04-16bit.png'});checks.push('Code, 8-bit assembly and 16-bit blue core follow in order');
 await page.getByRole('button',{name:'Продолжить вступление',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.intro-sequence')?.getAttribute('data-phase')==='4');await page.getByRole('button',{name:'Приостановить вступление',exact:true}).click();assert.equal(await intro.getAttribute('data-phase'),'4');await intro.locator('.core-canvas[data-loaded="true"]').waitFor();await page.getByRole('button',{name:'Начать разговор',exact:true}).waitFor();await page.screenshot({animations:'disabled',path:'docs/research/intro/05-3d.png'});checks.push('Story reaches actual GLB mascot and conversation action');
 await page.getByRole('button',{name:'Продолжить вступление',exact:true}).click();await intro.waitFor({state:'detached'});checks.push('Story completes automatically after approximately 24 seconds');
 await page.reload();await intro.waitFor();assert.equal(await intro.getAttribute('data-phase'),'0');await page.getByRole('button',{name:'Пропустить вступление',exact:true}).click();await intro.waitFor({state:'detached'});checks.push('Reload restarts; skip exits immediately');
 await page.getByRole('button',{name:'Повторить вступление'}).click();await intro.waitFor();await page.keyboard.press('Escape');await intro.waitFor({state:'detached'});checks.push('Replay and keyboard Escape work');
 await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await intro.waitFor();assert.equal(await intro.getAttribute('data-reduced'),'true');assert.equal(await intro.locator('canvas').count(),0);assert.equal(await intro.getAttribute('data-phase'),'4');
 for(const [width,height] of [[320,568],[390,844],[768,1024]]){await page.setViewportSize({width,height});const fits=await intro.evaluate(e=>e.scrollWidth<=e.clientWidth&&e.scrollHeight<=e.clientHeight+1);assert.ok(fits,'Intro fits '+width+'x'+height);}
 await page.screenshot({animations:'disabled',path:'docs/research/intro/06-reduced.png'});await page.getByRole('button',{name:'Начать разговор',exact:true}).click();await intro.waitFor({state:'detached'});checks.push('Reduced motion is static, readable and fits mobile/tablet screens');
 assert.equal(await page.locator('.brand-symbol rect').count(),4);assert.equal(await page.locator('.brand-symbol circle').count(),1);checks.push('Flat logo uses four squares and one blue circle');
 assert.deepEqual(errors,[]);checks.push('No uncaught JavaScript errors');
 await writeFile('docs/research/intro-tests.json',JSON.stringify({url,passed:checks.length,checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,checks}));
}finally{await context.close();await browser.close();}
