import assert from 'node:assert/strict';
import {randomUUID,randomBytes} from 'node:crypto';
import {hash} from 'argon2';
import {db,transaction} from '../server/db.js';
import {enqueueNotification,runNotificationOnce,retryNotification,notificationOverview} from '../server/outbox.js';
import {digest} from '../server/domain.js';
import type {NotificationSettings,TelegramCall} from '../server/telegram-notifications.js';
const database=new URL(process.env.DATABASE_URL||'');if(!['127.0.0.1','localhost'].includes(database.hostname)||!/_(test|ci)$/.test(database.pathname))throw Error('Use a dedicated loopback test/CI database');
const s:NotificationSettings={enabled:true,token:'123:synthetic',chatId:'-1001234567',botId:'123',origin:'https://example.invalid'};
const leadIds:string[]=[],visitors:string[]=[],jobs:string[]=[];const actor='outbox-'+randomUUID(),adminId=randomUUID(),password=randomBytes(24).toString('base64url');let cookie='',adminCookie='',passed=0,calls=0;
const ok:TelegramCall=async(method,body)=>{calls++;return method==='deleteMessage'?{ok:true,result:true}:{ok:true,result:{message_id:42,chat:{id:Number(body.chat_id)}}};};
async function check(name:string,fn:()=>Promise<void>){await fn();passed++;console.log('PASS',name);}
async function state(id:string){return (await db.query('SELECT * FROM notification_outbox WHERE id=$1',[id])).rows[0];}
async function fixture(enabled=true){const id=randomUUID();leadIds.push(id);await transaction(async c=>{
 await c.query("INSERT INTO leads(id,request_key,name,company,contact,channel,services,brief) VALUES($1,$2,'Synthetic','QA','qa@example.com','email',ARRAY['audit'],'Never send this private brief')",[id,randomUUID()]);
 for(const kind of ['data','callback'])await c.query('INSERT INTO consent_events(lead_id,kind,granted,version,document_hash,document_text) VALUES($1,$2,true,$3,$4,$5)',[id,kind,'synthetic-1','0'.repeat(64),'Synthetic consent only']);
 await enqueueNotification(c,id,{...s,enabled});
 });const job=(await db.query('SELECT id FROM notification_outbox WHERE lead_id=$1',[id])).rows[0]?.id;if(job)jobs.push(job);return {lead:id,job};}
const base='http://127.0.0.1:8787/api';async function req(path:string,body?:unknown,auth=cookie){return fetch(base+path,{method:body?'POST':'GET',headers:{Origin:'http://127.0.0.1:5178','X-SGS-Request':'1','Content-Type':'application/json',Cookie:auth},body:body?JSON.stringify(body):undefined});}
try{
 await check('Disabled notifications create no job and make no transport call',async()=>{const f=await fixture(false);assert.equal(f.job,undefined);const before=calls;assert.equal((await runNotificationOnce(db,{...s,enabled:false},ok)).status,'disabled');assert.equal(calls,before);});
 await check('Outbox insert rolls back with the lead and consent transaction',async()=>{const id=randomUUID();await assert.rejects(transaction(async c=>{await c.query("INSERT INTO leads(id,request_key,name,contact,channel,services) VALUES($1,$2,'QA','qa@example.com','email',ARRAY['audit'])",[id,randomUUID()]);await enqueueNotification(c,id,s);throw Error('rollback');}));assert.equal((await db.query('SELECT id FROM notification_outbox WHERE lead_id=$1',[id])).rowCount,0);assert.equal((await db.query('SELECT id FROM leads WHERE id=$1',[id])).rowCount,0);});
 await check('Unique event and two workers do not duplicate a delivery',async()=>{const f=await fixture();await transaction(c=>enqueueNotification(c,f.lead,s));assert.equal((await db.query('SELECT id FROM notification_outbox WHERE lead_id=$1',[f.lead])).rowCount,1);const before=calls;const results=await Promise.all([runNotificationOnce(db,s,ok),runNotificationOnce(db,s,ok)]);assert.equal(results.filter(x=>x.status==='sent').length,1);assert.equal(calls-before,1);assert.equal((await state(f.job)).message_id,'42');});
 await check('429 schedules a bounded retry and honours retry_after',async()=>{const f=await fixture();await runNotificationOnce(db,s,async()=>({ok:false,error_code:429,parameters:{retry_after:500}}));let row=await state(f.job);assert.equal(row.status,'retry');assert.ok(new Date(row.next_attempt_at).getTime()>Date.now()+490000);assert.equal((await runNotificationOnce(db,s,ok)).status,'idle');await db.query("UPDATE notification_outbox SET next_attempt_at=now()-interval '1 second' WHERE id=$1",[f.job]);await runNotificationOnce(db,s,ok);row=await state(f.job);assert.equal(row.status,'sent');assert.equal(row.attempts,2);});
 await check('Transport timeout becomes uncertain and is never automatically or blindly retried',async()=>{const f=await fixture();await runNotificationOnce(db,s,async()=>{throw Error('https://api.telegram.org/botSECRET')});const row=await state(f.job);assert.equal(row.status,'uncertain');assert.equal(row.error_code,'transport_unknown');const before=calls;await runNotificationOnce(db,s,ok);assert.equal(calls,before);assert.equal(await retryNotification(db,f.job,actor),false);});
 await check('403 can be retried only by an explicit operator action',async()=>{const f=await fixture();await runNotificationOnce(db,s,async()=>({ok:false,error_code:403,description:'private provider text'}));assert.equal((await state(f.job)).status,'failed');assert.equal(await retryNotification(db,f.job,actor),true);await runNotificationOnce(db,s,ok);assert.equal((await state(f.job)).status,'sent');assert.equal((await db.query("SELECT * FROM admin_audit WHERE actor=$1 AND action='notification_retry'",[actor])).rowCount,1);});
 await check('Expired unsent lease is recoverable, expired sending lease is uncertain',async()=>{
  const f=await fixture();await db.query("UPDATE notification_outbox SET status='leased',lease_token=$2,lease_until=now()-interval '1 second' WHERE id=$1",[f.job,randomUUID()]);await runNotificationOnce(db,s,ok);assert.equal((await state(f.job)).status,'sent');
  const g=await fixture(),token=randomUUID();await db.query("UPDATE notification_outbox SET status='sending',lease_token=$2,lease_until=now()-interval '1 second',attempts=1 WHERE id=$1",[g.job,token]);await db.query("INSERT INTO notification_attempts(notification_id,lease_token,operation) VALUES($1,$2,'send')",[g.job,token]);const before=calls;await runNotificationOnce(db,s,ok);assert.equal(calls,before);assert.equal((await state(g.job)).status,'uncertain');assert.equal((await db.query('SELECT outcome FROM notification_attempts WHERE lease_token=$1',[token])).rows[0].outcome,'uncertain');
 });
 await check('Deleted lead is cancelled before delivery and delivered message is removed',async()=>{
  const f=await fixture();await db.query('DELETE FROM leads WHERE id=$1',[f.lead]);const before=calls;await runNotificationOnce(db,s,ok);assert.equal((await state(f.job)).status,'cancelled');assert.equal(calls,before);
  const g=await fixture();await runNotificationOnce(db,s,ok);await db.query('DELETE FROM leads WHERE id=$1',[g.lead]);await runNotificationOnce(db,s,ok);assert.equal((await state(g.job)).status,'deleted');
 });
 await check('Deletion during an in-flight send retains IDs for subsequent removal',async()=>{const f=await fixture();await runNotificationOnce(db,s,async(method,body)=>{await db.query('DELETE FROM leads WHERE id=$1',[f.lead]);return ok(method,body);});assert.equal((await state(f.job)).lead_id,null);await runNotificationOnce(db,s,ok);assert.equal((await state(f.job)).status,'deleted');});
 await check('Changed destination and missing consent never send contacts',async()=>{const f=await fixture();await db.query("UPDATE notification_outbox SET target_chat='-1009999999' WHERE id=$1",[f.job]);const before=calls;await runNotificationOnce(db,s,ok);assert.equal((await state(f.job)).error_code,'target_changed');assert.equal(calls,before);const g=await fixture();await db.query('DELETE FROM consent_events WHERE lead_id=$1',[g.lead]);await runNotificationOnce(db,s,ok);assert.equal((await state(g.job)).error_code,'consent_missing');assert.equal(calls,before);});
 await check('A later withdrawn consent blocks a queued notification',async()=>{const f=await fixture();await db.query("INSERT INTO consent_events(lead_id,kind,granted,version,document_hash,document_text) VALUES($1,'data',false,'synthetic-1',$2,'Synthetic withdrawal')",[f.lead,'0'.repeat(64)]);const before=calls;await runNotificationOnce(db,s,ok);assert.equal(calls,before);assert.equal((await state(f.job)).error_code,'consent_missing');});
 await check('Source snapshot uses server times, drops secrets and cannot fake Telegram verification',async()=>{
  const r=await req('/session',{entry:{landing:'/',referrerHost:'search.example',utm:{utm_source:'search',utm_campaign:'autumn',utm_term:'test@example.com'},channel:'telegram_verified',at:'1900'}});assert.equal(r.status,200);cookie=r.headers.get('set-cookie')!.split(';')[0];visitors.push((await db.query('SELECT id FROM visitors WHERE token_hash=$1',[digest(cookie.split('=')[1])])).rows[0].id);
  await db.query('UPDATE visitors SET telegram_verified=true WHERE id=$1',[visitors.at(-1)]);
  await req('/session',{entry:{landing:'/?secret=x',referrerHost:'evil.example/path',utm:{utm_source:'social',utm_campaign:'token-secret'}}});
  const config=await(await req('/config')).json();assert.equal(config.attributionEnabled,true);assert.match(config.documents.data,/Synthetic notification disclosure/);
  const body={requestKey:randomUUID(),name:'Synthetic API',company:'QA',contact:'qa@example.com',channel:'email',services:['audit'],brief:'QA only',dataConsent:true,callbackConsent:true,marketingConsent:false,policyVersion:config.policyVersion,attribution:{channel:'telegram_verified',first:{at:'1900'}}};
  const response=await req('/leads',body);assert.equal(response.status,200,await response.clone().text());const id=(await response.json()).id;leadIds.push(id);const row=(await db.query('SELECT attribution FROM leads WHERE id=$1',[id])).rows[0];assert.equal(row.attribution.channel,'website');assert.equal(row.attribution.first.utm.utm_source,'search');assert.equal(row.attribution.last.utm.utm_source,'social');assert.equal(row.attribution.last.landing,null);assert.equal(row.attribution.first.utm.utm_term,undefined);assert.ok(new Date(row.attribution.first.at).getFullYear()>2025);
  jobs.push((await db.query('SELECT id FROM notification_outbox WHERE lead_id=$1',[id])).rows[0].id);assert.equal((await(await req('/leads',body)).json()).id,id);assert.equal((await db.query('SELECT id FROM notification_outbox WHERE lead_id=$1',[id])).rowCount,1);
 });
 await check('Authenticated CRM exposes queue and sources while guests cannot retry',async()=>{
  const job=jobs.at(-1)!;assert.equal((await req('/admin/notifications/'+job+'/retry',{})).status,401);
  await db.query('INSERT INTO admins(id,login,password_hash) VALUES($1,$2,$3)',[adminId,actor,await hash(password)]);const login=await req('/admin/login',{login:actor,password});assert.equal(login.status,200);adminCookie=login.headers.get('set-cookie')!.split(';')[0];
  const overview=await(await req('/admin/overview',undefined,adminCookie)).json();assert.equal(overview.notifications.enabled,true);assert.ok(overview.notifications.counts.some((x:any)=>x.status==='uncertain'));assert.equal((await req('/admin/notifications/'+job+'/retry',{},adminCookie)).status,409);
  const csv=await(await req('/admin/export/csv',undefined,adminCookie)).text();assert.match(csv,/"profile";"source"/);assert.match(csv,/utm_source=search/);
 });
 await check('Queue reporting contains metadata but no copied contact or provider payload',async()=>{const overview=JSON.stringify(await notificationOverview(db));assert.doesNotMatch(overview,/@example|private provider text|SECRET|api.telegram.org/);});
 console.log(JSON.stringify({passed,transportCalls:calls,realTelegramCalls:0}));
}finally{
 for(const id of jobs)await db.query('DELETE FROM notification_outbox WHERE id=$1',[id]);for(const id of leadIds)await db.query('DELETE FROM leads WHERE id=$1',[id]);for(const id of visitors)await db.query('DELETE FROM visitors WHERE id=$1',[id]);await db.query('DELETE FROM admins WHERE id=$1',[adminId]);await db.query('DELETE FROM admin_audit WHERE actor=$1',[actor]);await db.end();
}
