server {
    listen 80;
    server_name sgsit.ru www.sgsit.ru;
    server_tokens off;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/sgsit-acme;
        try_files $uri =404;
    }
    location / { return 301 https://sgsit.ru$request_uri; }
}
