import {useEffect,useState} from 'react';
import {api} from '../api';
import {auditFields,auditSchema,auditSections,priorities,type AuditRecord,type AuditDocument} from '../../shared/audit';
export function AuditEditor({leadId,onSaved,onDirty}:{leadId:string,onSaved:()=>void,onDirty:(dirty:boolean)=>void}){
 const [record,setRecord]=useState<AuditRecord|null>(null);const [doc,setDoc]=useState<AuditDocument|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [dirty,setDirty]=useState(false);const [section,setSection]=useState(0);
 async function load(){setBusy(true);try{const r=await api<AuditRecord>(`/admin/leads/${leadId}/audit-data`);setRecord(r);setDoc(r.document);setDirty(false);setError('');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{void load();},[leadId]);
 useEffect(()=>{onDirty(dirty);},[dirty,onDirty]);
 useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty]);
 function change(next:AuditDocument){setDoc(next);setDirty(true);setNotice('');}
 async function save(status:'draft'|'ready'){
  if(!doc||!record)return;setError('');setNotice('');const next={...doc,status};
  if(!auditSchema.safeParse(next).success){setError('Для готового документа заполните границы, резюме и все поля включённых разделов. Для исключённых укажите причину.');return;}
  setBusy(true);try{const r=await api<AuditRecord>(`/admin/leads/${leadId}/audit-data`,{version:record.version,document:next},'PATCH');setRecord(r);setDoc(r.document);setDirty(false);setNotice('Документ сохранён. Версия '+r.version);onSaved();}catch(e:any){setError(e.status===409?'Документ уже изменён в другой вкладке. Скопируйте свои правки перед загрузкой актуальной версии.':e.message);}finally{setBusy(false);}
 }
 if(!doc||!record)return <section className="audit-editor"><h3>Документ аудита</h3>{error?<><p className="error" role="alert">{error}</p><button type="button" onClick={load}>Повторить загрузку</button></>:<p role="status">Загружаю документ…</p>}</section>;
 const current=doc.sections[section];
 return <section className="audit-editor"><header><h3>Документ аудита</h3><span className="stage-badge">{dirty?'Есть несохранённые правки':record.document.status==='ready'?'Готов к передаче':'Черновик'} · v{record.version}</span></header><p className="muted">Выводы и рекомендации заполняет специалист по проверенным данным. Сохранение не отправляет документ заказчику.</p><label>Границы исследования<textarea value={doc.scope} maxLength={2000} rows={3} onChange={e=>change({...doc,scope:e.target.value})}/></label><label>Резюме для руководителя<textarea value={doc.summary} maxLength={2000} rows={3} onChange={e=>change({...doc,summary:e.target.value})}/></label><label>Раздел аудита<select value={section} onChange={e=>setSection(Number(e.target.value))}>{auditSections.map((s,i)=><option key={s.id} value={i}>{i+1}. {s.title}</option>)}</select></label><fieldset key={current.id}><legend>{auditSections[section].title}</legend><label className="audit-included"><input type="checkbox" checked={current.included} onChange={e=>change({...doc,sections:doc.sections.map((s,i)=>i===section?{...s,included:e.target.checked}:s)})}/>Включён в объём исследования</label>{current.included?<><div className="form-grid">{Object.entries(auditFields).map(([key,label])=><label key={key}>{label}<textarea rows={3} maxLength={1000} value={current[key as keyof typeof auditFields]} onChange={e=>change({...doc,sections:doc.sections.map((s,i)=>i===section?{...s,[key]:e.target.value}:s)})}/></label>)}</div><label>Приоритет<select value={current.priority} onChange={e=>change({...doc,sections:doc.sections.map((s,i)=>i===section?{...s,priority:e.target.value as typeof s.priority}:s)})}>{Object.entries(priorities).map(([key,title])=><option value={key} key={key}>{title}</option>)}</select></label></>:<label>Почему раздел исключён<textarea maxLength={1000} rows={3} value={current.exclusion} onChange={e=>change({...doc,sections:doc.sections.map((s,i)=>i===section?{...s,exclusion:e.target.value}:s)})}/></label>}</fieldset>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}<div className="brief-navigation"><button type="button" className="secondary" disabled={busy} onClick={()=>save('draft')}>Сохранить черновик</button><button type="button" className="primary" disabled={busy} onClick={()=>save('ready')}>Подготовить к передаче</button>{!dirty&&<a className="secondary" href={`/api/admin/leads/${leadId}/audit`}>Скачать документ HTML</a>}<button type="button" className="text-link" disabled={busy} onClick={()=>{if(!dirty||window.confirm('Загрузить сохранённую версию? Несохранённые правки будут потеряны.'))void load();}}>Загрузить сохранённую версию</button></div><p className="muted">HTML можно открыть в браузере и сохранить в PDF через печать. В выгрузку входят только сохранённые изменения.</p></section>;
}
