import {useState} from 'react';
import {ArrowUpRight,CheckCircle2} from 'lucide-react';
import {api,serviceNames} from '../api';
import {BriefBuilder} from './BriefBuilder';
export function LeadForm({config,brief,openDoc}:{config:any,brief:string,openDoc:(key:string)=>void}){const [task,setTask]=useState(brief);const [builder,setBuilder]=useState(false);const [selected,setSelected]=useState(['audit']);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [done,setDone]=useState('');const [key]=useState(()=>crypto.randomUUID());const [channel,setChannel]=useState('email');if(done)return <div className="success-panel"><CheckCircle2 size={52}/><h3>Контекст передан.</h3><p>Заявка сохранена. Команда SGS IT увидит выбранные услуги и ваш бриф в CRM.</p><span className="mono">Заявка {done.slice(0,8)}</span></div>;
 if(config.mode==='preview')return <div className="preview-brief"><h3>Аудит начинается с данных.</h3><p>Это демонстрационный стенд SGS IT. Приём заявок пока закрыт; введённые в чат сообщения обрабатываются только в браузере.</p><p>Результат будущего аудита: качество данных, аналитика продаж, маркетинга и операций, ограничения и приоритетные рекомендации.</p><BriefBuilder preview/><a className="secondary" href="https://github.com/rdsolod-ui/sgs-it" target="_blank" rel="noreferrer">Разработка проекта ↗</a></div>;
 return <form className="lead-form" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);const f=new FormData(e.currentTarget);try{const r=await api('/leads',{requestKey:key,name:f.get('name'),company:f.get('company'),contact:f.get('contact'),channel,services:selected,brief:f.get('brief'),dataConsent:f.get('data')==='on',callbackConsent:f.get('callback')==='on',marketingConsent:f.get('marketing')==='on',policyVersion:config.policyVersion});setDone(r.id);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
 <p>Выберите следующий шаг. Можно несколько — обсудим задачу и подберём полезный формат.</p><div className="service-options">{Object.entries(serviceNames).map(([k,v])=><label key={k} className={selected.includes(k)?'selected':''}><input type="checkbox" checked={selected.includes(k)} onChange={()=>setSelected(s=>s.includes(k)?s.filter(x=>x!==k):[...s,k])}/>{v}</label>)}</div>
 {!config.legalReady&&<p className="notice">Тестовый приём заявок. Введите вымышленные данные: юридические документы пока проходят подготовку.</p>}
 <button type="button" className="secondary" onClick={()=>setBuilder(x=>!x)}>{builder?'Свернуть конструктор':'Составить бриф за 6 вопросов'}</button>{builder&&<BriefBuilder onApply={setTask}/>}
 <div className="form-grid"><label>Как к вам обращаться<input name="name" required minLength={2} maxLength={100} autoComplete="name" placeholder="Имя"/></label><label>Компания<input name="company" maxLength={160} autoComplete="organization" placeholder="Название компании"/></label></div><div className="form-grid"><label>Канал связи<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="email">Email</option><option value="phone">Телефон</option><option value="telegram">Telegram</option></select></label><label>Контакт<input name="contact" required type={channel==='email'?'email':channel==='phone'?'tel':'text'} maxLength={160} placeholder={channel==='email'?'name@company.ru':channel==='phone'?'+7 900 000-00-00':'@username'}/></label></div><label>Какую задачу решаем<textarea name="brief" value={task} onChange={e=>setTask(e.target.value)} maxLength={2500} rows={3} placeholder="Какие данные есть и что хочется изменить"/></label>
 <div className="consents"><label><input name="data" type="checkbox" required/><span>Даю отдельное <button type="button" className="text-link" onClick={()=>openDoc('data')}>согласие на обработку персональных данных</button> для заявки.</span></label><label><input name="callback" type="checkbox" required/><span>Прошу <button type="button" className="text-link" onClick={()=>openDoc('callback')}>связаться со мной</button> по выбранному каналу по моей заявке.</span></label><label><input name="marketing" type="checkbox"/><span>Хочу получать новости и предложения. <button type="button" className="text-link" onClick={()=>openDoc('marketing')}>Отдельное рекламное согласие</button>, необязательно.</span></label></div>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" disabled={busy||!selected.length||!config.canCollect}>{busy?'Сохраняю…':'Передать задачу команде'}<ArrowUpRight size={18}/></button><p className="form-footnote">Без подписки на рассылку по умолчанию. <button type="button" className="text-link" onClick={()=>openDoc('privacy')}>Политика обработки данных</button></p></form>;
}
