import {useState} from 'react';
import {api} from '../api';
const labels:Record<string,string>={pending:'В очереди',leased:'Подготовка',sending:'Отправляется',retry:'Ожидает повтора',sent:'Доставлено',failed:'Ошибка',uncertain:'Исход неизвестен',cancelled:'Отменено',deleted:'Удалено из канала'};
type Item={id:string,lead_id:string|null,operation:string,status:string,attempts:number,error_code:string|null};
type Report={enabled:boolean,counts:{status:string,count:number,oldest_seconds:number}[],items:Item[],worker:{heartbeat_at:string,error_code:string|null}|null};
export function NotificationPanel({report,onOpen,onReload}:{report?:Report,onOpen:(id:string)=>void,onReload:()=>Promise<void>}){
 const [error,setError]=useState(''),[busy,setBusy]=useState('');if(!report)return null;
 const stale=!report.worker||Date.now()-new Date(report.worker.heartbeat_at).getTime()>90000;
 return <section className="notification-panel" aria-label="Доставка Telegram"><h2>Доставка Telegram</h2><p>{report.enabled?'Очередь включена.':'Уведомления отключены. Новые задания не создаются.'} {report.enabled&&(stale?'Нет свежего сигнала от обработчика.':report.worker?.error_code?'Обработчик сообщил об ошибке.':'Обработчик отвечает.')}</p>
 <p>{report.counts.map(x=>`${labels[x.status]||x.status}: ${x.count}`).join(' · ')||'Очередь пуста.'}</p>{report.counts.some(x=>['pending','retry'].includes(x.status))&&<p className="muted">Возраст очереди: {Math.ceil(Math.max(...report.counts.filter(x=>['pending','retry'].includes(x.status)).map(x=>x.oldest_seconds))/60)} мин.</p>}
 {error&&<p className="error" role="alert">{error}</p>}<details><summary>Задания доставки ({report.items.length})</summary><div className="table-wrap"><table><thead><tr><th>Заявка</th><th>Действие</th><th>Статус</th><th>Попытки</th><th>Следующий шаг</th></tr></thead><tbody>{report.items.map(item=><tr key={item.id}><td>{item.lead_id?<button className="text-link" onClick={()=>onOpen(item.lead_id!)}>{item.lead_id.slice(0,8)}</button>:'Заявка удалена'}</td><td>{item.operation==='delete'?'Удаление сообщения':'Уведомление'}</td><td>{labels[item.status]||item.status}<span>{item.error_code}</span></td><td>{item.attempts}</td><td>{item.status==='uncertain'?'Проверьте канал. Автоповтор запрещён.':item.status==='failed'&&report.enabled&&(item.lead_id||item.operation==='delete')?<button className="secondary" disabled={Boolean(busy)} onClick={async()=>{setBusy(item.id);setError('');try{await api(`/admin/notifications/${item.id}/retry`,{});await onReload();}catch(e:any){setError(e.message);}finally{setBusy('');}}}>Повторить после устранения ошибки</button>:'—'}</td></tr>)}</tbody></table></div></details></section>;
}
