import {lazy,Suspense,useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowUpRight,Sun,Moon,Plus,X,RotateCcw,ChevronRight,Layers3,ShieldCheck} from 'lucide-react';
import {api} from './api';
import {salesSummary,salesBrief,actionLabels,type SalesState,type SalesAction,type SalesChoice} from '../shared/sales';
import {Modal} from './components/Modal';
import {Demo} from './components/Demo';
import {LeadForm} from './components/LeadForm';
import {BrandMark} from './components/BrandMark';
import {Intro} from './components/Intro';
const Core=lazy(()=>import('./components/Core').then(m=>({default:m.Core})));
type Message={role:'user'|'assistant',text:string,demo?:string|null};
const docTitles:Record<string,string>={privacy:'Персональные данные',cookies:'Файлы cookie',data:'Согласие на обработку данных',callback:'Запрос обратной связи',marketing:'Рекламное согласие'};
export default function App(){const [dark,setDark]=useState(document.documentElement.dataset.theme==='dark');const [reduced,setReduced]=useState(matchMedia('(prefers-reduced-motion: reduce)').matches);const [intro,setIntro]=useState(!location.pathname.startsWith('/legal/'));const [config,setConfig]=useState<any>(null);const [messages,setMessages]=useState<Message[]>([]);const [sales,setSales]=useState<SalesState|null>(null);const [choices,setChoices]=useState<SalesChoice[]>([]);const [text,setText]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [modal,setModal]=useState('');const [doc,setDoc]=useState(()=>location.pathname.startsWith('/legal/')&&docTitles[location.pathname.split('/')[2]]?location.pathname.split('/')[2]:'');const [cookies,setCookies]=useState(!localStorage.getItem('sgs-cookies'));const [responding,setResponding]=useState(false);const end=useRef<HTMLDivElement>(null);const input=useRef<HTMLTextAreaElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const finishIntro=useCallback(()=>setIntro(false),[]);
 useEffect(()=>{Promise.all([api('/config'),api('/session',{})]).then(([c,s])=>{setConfig(c);setMessages(s.messages);setSales(s.sales||null);setChoices(s.choices||[]);}).catch(e=>setError(e.message));const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);media.addEventListener('change',update);return()=>{media.removeEventListener('change',update);if(timer.current)clearTimeout(timer.current);};},[]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:reduced?'instant':'smooth',block:'end'});},[messages,busy]);
 useEffect(()=>{const tg=(window as any).Telegram?.WebApp;if(!tg?.initData)return;tg.ready();tg.expand();if(tg.initData)api('/telegram',{initData:tg.initData}).catch(()=>{});},[]);
 useEffect(()=>{const tg=(window as any).Telegram?.WebApp;if(!tg?.initData||!tg.isVersionAtLeast('6.1'))return;const back=()=>{setDoc('');setModal('');};if(modal||doc){tg.BackButton.show();tg.BackButton.onClick(back);}else tg.BackButton.hide();return()=>tg.BackButton.offClick(back);},[modal,doc]);
 function theme(){const next=!dark;setDark(next);document.documentElement.dataset.theme=next?'dark':'light';localStorage.setItem('sgs-theme',next?'dark':'light');document.querySelector('meta[name="theme-color"]')?.setAttribute('content',next?'#11171e':'#ecece8');}
 async function send(value=text,action?:SalesAction){if(!value.trim()||busy||!config)return;setError('');setText('');setMessages(m=>[...m,{role:'user',text:value}]);setBusy(true);try{const r=await api('/chat',{...(action?{action}:{message:value}),...(sales?{revision:sales.revision}:{})});setMessages(m=>[...m,{role:'assistant',text:r.text,demo:r.demo}]);setSales(r.sales||null);setChoices(r.choices||[]);if(r.ui==='lead')setModal('lead');setResponding(true);timer.current=setTimeout(()=>setResponding(false),2200);}catch(e:any){setError(e.message);setText(action?'':value);if(e.status===409){const fresh=await api('/session',{}).catch(()=>null);if(fresh){setMessages(fresh.messages);setSales(fresh.sales||null);setChoices(fresh.choices||[]);}}}finally{setBusy(false);}}
 const mascotState=modal?'presenting':busy?'thinking':responding?'responding':text?'listening':'idle';
 return <main tabIndex={-1} className={`experience ${messages.length?'in-conversation':''}`}>
 <header className="site-header"><a className="brand" href={import.meta.env.BASE_URL} aria-label="SGS IT — главная"><BrandMark className="brand-symbol"/><span>SGS<span className="brand-it">IT</span></span></a><div className="header-product"><span className="hairline"/>ИНТЕЛЛЕКТ ВАШЕГО БИЗНЕСА</div><div className="header-actions"><button className="header-demo" onClick={()=>setModal('overview')}>Возможности parkops<ArrowUpRight size={15}/></button><button className="icon-button theme-button" onClick={theme} aria-label={dark?'Включить светлую тему':'Включить тёмную тему'}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button></div></header>
 <section className="stage" aria-label="Знакомство с parkops"><div className="stage-coordinate"><span className="status-dot"/>PARKOPS / BUSINESS OPERATING SYSTEM</div><div className="title-block"><p className="eyebrow">ДАННЫЕ. ПРОЦЕССЫ. РЕШЕНИЯ.</p><h1>Ваш бизнес.<br/><span>В одной системе.</span></h1><p className="intro-copy">Разрозненные данные становятся ясной картиной.<br className="desktop-break"/> Начните с разговора — я покажу, как.</p></div>
 <div className="sculpture-stage"><span className="orbit orbit-one"/><span className="orbit orbit-two"/><Suspense fallback={<div className="core-fallback"><i/><i/><i/><i/></div>}><Core state={mascotState} dark={dark} reduced={reduced||intro}/></Suspense><div className="core-caption"><span className={`status-dot ${busy?'pulsing':''}`}/><span>СИНК</span><span className="caption-divider">/</span><span>{busy?'Собираю контекст':responding?'Формулирую ответ':text?'Слушаю вас':'Готов к вашей задаче'}</span></div></div>
 <div className="module-labels" aria-hidden="true"><span>CRM & ПРОДАЖИ</span><span>МАРКЕТИНГ</span><span>ОПЕРАЦИИ</span></div>
 </section>
 <section className="conversation" aria-label="Чат с Синком">{messages.length>0&&<div className="chat-history" role="log" aria-label="История диалога" aria-live="polite">{messages.map((m,i)=><article key={i} className={`message ${m.role}`}><span className="message-who">{m.role==='assistant'?'СИНК':'ВЫ'}</span><p>{m.text}</p>{m.demo&&<button className="inline-demo" onClick={()=>setModal(m.demo!)}><Layers3 size={15}/>{m.demo==='audit'?'Как выглядит аудит':'Посмотреть на примере'}<ArrowUpRight size={15}/></button>}</article>)}{busy&&<div className="thinking" role="status"><i/><i/><i/><span>Собираю контекст</span></div>}<div className="sales-actions" aria-label="Следующий шаг">{choices.map(choice=><button type="button" key={choice.id} disabled={busy} onClick={()=>send(actionLabels[choice.id],choice.id)}>{choice.label}</button>)}</div><div ref={end}/></div>}
 {!messages.length&&<div className="suggestions"><button onClick={()=>send('Покажи возможности parkops')}><Layers3 size={15}/>Показать parkops</button><button onClick={()=>send('Хочу навести порядок в данных')}>Навести порядок в данных<ArrowUpRight size={14}/></button><button onClick={()=>setModal('lead')}>Начать с аудита<Plus size={16}/></button></div>}
 <form className="composer" onSubmit={e=>{e.preventDefault();send();}}><div className="composer-mark" aria-hidden="true">✳</div><textarea ref={input} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}} placeholder="Задача бизнеса…" aria-label="Сообщение Синку" maxLength={2800} rows={1} disabled={!config}/><button className="send-button" aria-label="Отправить сообщение" disabled={!text.trim()||busy||!config}><ArrowUp size={22}/></button></form>
 {error&&<div role="alert" className="chat-error">{error}<button className="text-link" onClick={()=>location.reload()}>Обновить</button></div>}
 <div className="composer-footer"><span><span className="status-dot"/>{config?.mode==='openai'?'AI-консультант':config?.mode==='preview'?'Демонстрационный стенд':'Демо-режим'}<span className="dot-separator">·</span>{config?.mode==='preview'?'Без отправки сообщений на сервер':'Контакты — только в форме заявки'}</span><button onClick={()=>setModal('lead')}>Связаться с командой<ArrowUpRight size={13}/></button></div>
 </section>
 <footer className="site-footer"><span>© {new Date().getFullYear()} SGS IT<span className="footer-company"> / ООО «ВоркСинк Системс»</span></span><div><button onClick={()=>setDoc('privacy')}>Правовая информация</button><button onClick={()=>setDoc('cookies')}>Cookie</button><button className="replay" onClick={()=>setIntro(true)} aria-label="Повторить вступление"><RotateCcw size={13}/></button></div></footer>
 {cookies&&<aside className="cookie-note" aria-label="Настройки cookie"><ShieldCheck size={19}/><p>Только необходимые cookie.<br/><button className="text-link" onClick={()=>setDoc('cookies')}>Что мы сохраняем</button></p><button aria-label="Принять только необходимые cookie" onClick={()=>{localStorage.setItem('sgs-cookies','essential-only');setCookies(false);}}>Понятно<ChevronRight size={15}/></button></aside>}
 {intro&&<Intro dark={dark} reduced={reduced} onFinish={finishIntro}/>}
 {modal&&<Modal title={modal==='lead'?'Начнём с вашей задачи':modal==='audit'?'Аудит, который даёт направление':'Знакомьтесь: parkops'} onClose={()=>setModal('')} wide={modal!=='lead'}>{modal==='lead'?config?<LeadForm config={config} brief={sales&&Object.keys(sales.profile).length?(sales.confirmed?'Подтверждено посетителем':'Резюме ещё не подтверждено')+'\n'+salesSummary(sales):messages.filter(m=>m.role==='user').map(m=>m.text).join('\n').slice(0,2500)} salesRevision={sales?.revision} initialAnswers={sales?salesBrief(sales):undefined} selectedOffer={sales?.selectedOffer||undefined} openDoc={setDoc}/>:<p>Подключение…</p>:<Demo kind={modal} onLead={()=>setModal('lead')}/>}</Modal>}
 {doc&&<Modal title={docTitles[doc]} onClose={()=>setDoc('')}><div className="legal-text">{config?.documents?.[doc]||'Документ загружается…'}</div><p className="muted">Версия: {config?.policyVersion||'—'}</p></Modal>}
 </main>;
}
